apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: prod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: yourdockerhubuser/node-api:v1
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_PORT
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASS
