apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
  namespace: prod
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS items (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL
    );
    INSERT INTO items (name) VALUES ('item1'), ('item2'), ('item3'), ('item4'), ('item5');
